language: python
python:
  - "2.7"

os:
  - linux
  - osx

install: pip install -r requirements.txt
script: python test/run

notifications:
  email:
    recipients:
      - eric@sunlightfoundation.com
      - tauberer@govtrack.us
      - dwillis@gmail.com
    on_success: change
    on_failure: change
